### ISSUE TITLE
arduio安装了M5Unit-UHF-RFID，编译出来还是会报错

### ISSUE THREAD

**Issue by cannnnnnnnnnnn** [m5stack/UNIT_UHF_RFID#3]
编译的是example里面的例子
`C:\Users\39080\AppData\Local\Temp\.arduinoIDE-unsaved20221128-40772-tbak2i.8a1fo\Unit_RFID_M5Core\Unit_RFID_M5Core.ino:22:10: fatal error: Unit_UHF_RFID.h: No such file or directory
 #include "Unit_UHF_RFID.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Unit_UHF_RFID.h 的替代方案：[]
ResolveLibrary(Unit_UHF_RFID.h)
  -> 候选: []
为 “SD.h” 找到了多个库
  使用：C:\Users\39080\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\SD
  未使用：C:\Users\39080\AppData\Local\Arduino15\libraries\SD
使用 0.4.3 版本的 M5Stack 库，在列出的文件夹中：C:\Users\39080\Documents\Arduino\libraries\M5Stack
使用 2.0.0 版本的 SPI 库，在列出的文件夹中：C:\Users\39080\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\SPI
使用 2.0.0 版本的 Wire 库，在列出的文件夹中：C:\Users\39080\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\Wire
使用 2.0.0 版本的 FS 库，在列出的文件夹中：C:\Users\39080\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\FS
使用 2.0.0 版本的 SPIFFS 库，在列出的文件夹中：C:\Users\39080\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\SPIFFS
使用 2.0.0 版本的 SD 库，在列出的文件夹中：C:\Users\39080\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\SD
使用 0.1.1 版本的 M5GFX 库，在列出的文件夹中：C:\Users\39080\Documents\Arduino\libraries\M5GFX
exit status 1

Compilation error: Unit_UHF_RFID.h: No such file or directory`

使用的是core2这款板子，但是怎么编译都是这里报错，我试着修改包名和头文件名一致，但是还是报错

**Comment by TinyuZhao** [comment]
你没有在Arduino中安装M5Unit-UHF-RFID 这个库
可以参看这个[教程](https://docs.m5stack.com/zh_CN/quick_start/library)

**Comment by cannnnnnnnnnnn** [comment]
> M5Unit-UHF-RFID

是的，这个库我是安装了的，但是还是会报错，就感觉很奇怪

**Comment by cannnnnnnnnnnn** [comment]
> 你没有在Arduino中安装M5Unit-UHF-RFID 这个库 可以参看这个[教程](https://docs.m5stack.com/zh_CN/quick_start/library)

在报错了之后，我还把对应的库文件名称改成了头文件名称，但是还是会报错

**Comment by TinyuZhao** [comment]
我这边没有问题的哦，不需要改任何东西就可以
<img width="881" alt="image" src="https://user-images.githubusercontent.com/44396641/209795422-40e5ae48-012b-4c80-8aac-14a5c65b3571.png">

**Comment by cannnnnnnnnnnn** [comment]
请问一下可不可以在gitee上同步一下仓库，在github上有些资源链接都打不开

**Comment by TinyuZhao** [comment]
> 请问一下可不可以在gitee上同步一下仓库，在github上有些资源链接都打不开

https://github.com/bannedbook/fanqiang
