### ISSUE TITLE
Can I set Japanese Frequency?

### ISSUE THREAD

**Issue by uecken** [m5stack/UNIT_UHF_RFID#5]
TELEC shows below frequency.
![image](https://github.com/m5stack/M5Unit-UHF-RFID/assets/5786149/8cbbf6cf-4c63-42d7-9d2b-5c296361b560)

https://www.telec.or.jp/services/tech/criterion/t242_01.html

Can I set above some frequency to JRD-4035?

**Comment by Tinyu-Zhao** [comment]
You can see the relevant instructions on page 29 of this [PDF](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/unit/uhf_rfid/MagicRF%20M100%26QM100_Firmware_manual_cn.pdf) about "4.17.

The English [PDF](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/unit/uhf_rfid/MagicRF%20M100%26QM100_Firmware_manual_en.pdf) in the "Set work area" column can see the relevant instructions
